test:
before_script: # configure a headless display to test plot generation
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  script:
  - apt-get update -qy
  - apt-get install -y python3-dev python3-numpy python3-tk
  - wget http://bootstrap.pypa.io/get-pip.py
  - python3 get-pip.py
  - make install clean tests
pages:
  stage: deploy
  script:
  - mkdir .public
  - cp -r docs/* .public
  - mv .public public
  artifacts:
    paths:
    - public
  only:
  - master
